### ISSUE TITLE
Problem z zadaniem 3

### ISSUE THREAD

**Issue by fexjo** [korona-science/homework-fexjo#1]
Hej, mógłbyś zerknąć jaki mam błąd w zadaniu 3? Chyba robię wszystko jak należy a ciągle żaden test mi nie przechodzi. Dzięki wielkie!

**Comment by RouNNdeL** [comment]
Brakuje ci importu obiektu `datetime`.

**Comment by fexjo** [comment]
No jasne dzięki wielkie!!!

**Comment by RouNNdeL** [comment]
Ale raczej nie importuje się modułów w funkcji, można to robić w specyficznych przypadkach, ale tutaj takiego nie ma ;)
